#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\RazorTemplates\EmailTemplate.cshtml"
    using AcknowledgementsTracker.Business.Interfaces;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class _RazorTemplates_EmailTemplate_cshtml : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 4 "..\..\RazorTemplates\EmailTemplate.cshtml"

    public string BeneficiaryName { get; set; }
    public string AuthorName { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n    <title></title>\r\n</h" +
"ead>\r\n<body>\r\n    <article>\r\n        <header>\r\n            <h2>Congratulations, " +
"");


            
            #line 16 "..\..\RazorTemplates\EmailTemplate.cshtml"
                            Write(BeneficiaryName.Split()[0]);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n        </header>\r\n        <section>\r\n            <p>\r\n                You" +
" have been acknowledged by ");


            
            #line 20 "..\..\RazorTemplates\EmailTemplate.cshtml"
                                         Write(AuthorName);

            
            #line default
            #line hidden
WriteLiteral(" on Proxiad Bulgaria\'s Acknowledgements Tracker!<br />\r\n                Go check " +
"it out on <a href=\"#\">Acknowledgements Tracker</a>\r\n            </p>\r\n        </" +
"section>\r\n    </article>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
